-- $BEGIN

INSERT INTO mamba_dim_orders (order_id, uuid, order_type_id, concept_id, patient_id, encounter_id, accession_number,
                              order_number, orderer, instructions, date_activated, auto_expire_date, date_stopped,
                              order_reason, creator, date_created, voided, voided_by, date_voided, void_reason,
                              order_reason_non_coded, urgency, previous_order_id, order_action, comment_to_fulfiller,
                              care_setting, scheduled_date, order_group_id, sort_weight, fulfiller_comment,
                              fulfiller_status)
SELECT order_id,
       uuid,
       order_type_id,
       concept_id,
       patient_id,
       encounter_id,
       accession_number,
       order_number,
       orderer,
       instructions,
       date_activated,
       auto_expire_date,
       date_stopped,
       order_reason,
       creator,
       date_created,
       voided,
       voided_by,
       date_voided,
       void_reason,
       order_reason_non_coded,
       urgency,
       previous_order_id,
       order_action,
       comment_to_fulfiller,
       care_setting,
       scheduled_date,
       order_group_id,
       sort_weight,
       fulfiller_comment,
       fulfiller_status
FROM mamba_source_db.orders;

-- $END