-- $BEGIN
CALL sp_mamba_drop_some_tables_before_incremental_update;

CALL sp_mamba_dim_concept_incremental_update;

CALL sp_mamba_dim_concept_answer_incremental_update;

CALL sp_mamba_dim_person_incremental_update;

CALL sp_mamba_dim_user_incremental_update;

CALL sp_mamba_dim_encounter_incremental_update;

CALL sp_mamba_dim_encounter_type_incremental_update;

CALL sp_mamba_dim_relationship_incremental_update;

CALL sp_mamba_dim_orders_incremental_update;

CALL sp_mamba_dim_json_incremental_create;

CALL sp_mamba_dim_concept_metadata_create;

CALL sp_mamba_dim_concept_metadata_incremental_insert;

CALL sp_mamba_z_encounter_obs_incremental_update;

CALL sp_mamba_flat_encounter_table_incremental_create_all;

CALL sp_mamba_flat_encounter_table_incremental_insert_all;

CALL sp_mamba_reset_flags_for_incremental_updates;

-- $END