-- $BEGIN
INSERT INTO mamba_dim_users (user_id,
                             system_id,
                             username,
                             creator,
                             person_id,
                             uuid,
                             email,
                             retired,
                             date_created,
                             date_changed,
                             changed_by,
                             date_retired,
                             retired_by,
                             retire_reason)
SELECT user_id,
       system_id,
       username,
       creator,
       person_id,
       uuid,
       email,
       retired,
       date_created,
       date_changed,
       changed_by,
       date_retired,
       retired_by,
       retire_reason
FROM mamba_source_db.users;
-- $END