#!/bin/bash

# Enable strict error handling
set -euo pipefail
IFS=$'\n\t'

# Script constants
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"

# Security validation functions
validate_database_name() {
    local db_name="$1"
    # Allow only alphanumeric, underscore, and dash characters
    if [[ ! "$db_name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
        echo "Error: Invalid database name: $db_name" >&2
        echo "Database names must contain only alphanumeric characters, underscores, and dashes" >&2
        exit 1
    fi
    if [[ ${#db_name} -gt 64 ]]; then
        echo "Error: Database name too long: $db_name (max 64 characters)" >&2
        exit 1
    fi
}

validate_path() {
    local path="$1"
    local base_dir="$2"
    
    # Resolve to absolute path
    local resolved_path
    resolved_path=$(realpath -m "$path" 2>/dev/null) || {
        echo "Error: Invalid path: $path" >&2
        exit 1
    }
    
    # Check if path is within allowed base directory
    if [[ -n "$base_dir" ]]; then
        local resolved_base
        resolved_base=$(realpath -m "$base_dir" 2>/dev/null) || {
            echo "Error: Invalid base directory: $base_dir" >&2
            exit 1
        }
        if [[ "$resolved_path" != "$resolved_base"* ]]; then
            echo "Error: Path traversal attempt detected: $path" >&2
            echo "Path must be within: $base_dir" >&2
            exit 1
        }
    fi
    
    echo "$resolved_path"
}

# Validate schema name to prevent SQL injection
validate_schema_name() {
    local schema="$1"
    # Allow only alphanumeric, underscore characters
    if [[ ! "$schema" =~ ^[a-zA-Z0-9_]+$ ]]; then
        echo "Error: Invalid schema name: $schema" >&2
        echo "Schema names must contain only alphanumeric characters and underscores" >&2
        exit 1
    fi
    if [[ ${#schema} -gt 64 ]]; then
        echo "Error: Schema name too long: $schema (max 64 characters)" >&2
        exit 1
    fi
}

# Validate integer parameters
validate_integer() {
    local value="$1"
    local param_name="$2"
    local min="${3:-0}"
    local max="${4:-2147483647}"
    
    if [[ ! "$value" =~ ^[0-9]+$ ]]; then
        echo "Error: Invalid ${param_name}: must be an integer, got: ${value}" >&2
        exit 1
    fi
    
    if [[ $value -lt $min || $value -gt $max ]]; then
        echo "Error: ${param_name} out of range: ${value} (must be between ${min} and ${max})" >&2
        exit 1
    fi
}

# Cleanup trap
cleanup() {
    local exit_code=$?
    # Clean up temporary files
    if [[ -n "${temp_file:-}" ]] && [[ -f "${temp_file}" ]]; then
        rm -f "${temp_file}"
    fi
    if [[ -n "${temp_file_no_tildes:-}" ]] && [[ -f "${temp_file_no_tildes}" ]]; then
        rm -f "${temp_file_no_tildes}"
    fi
    exit $exit_code
}
trap cleanup EXIT ERR INT TERM

# Usage info
function show_help() {
cat << EOF

Usage: ${0##*/} [-h] [-d DATABASE] [-v VW_MAKEFILE] [-s SP_MAKEFILE]...
Reads file paths in the MAKE FILEs and for each file, uses the content to create a stored procedure or a view. Stored procedures are
put in the create_stored_procedures.sql file and views in a create_views.sql file.

    -h                          display this help and exit
    -t CONFIG_DIR               JSON configuration file
    -n DB_ENGINE                Database Vendor/Engine. One of: mysql|postgres|sqlserver|oracle
    -d SOURCE_DATABASE          the Source Database (openmrs database).
    -a ANALYSIS_DATABASE        the Target/Analysis Database (where the ETL data is stored).
    -v VW_MAKEFILE              file with a list of all files with views
    -s SP_MAKEFILE              file with a list of all files with stored procedures
    -k SCHEMA                   schema in which the views and or stored procedures will be put
    -o OUTPUT_FILE              the file where the compiled output will be put
    -b BUILD_FLAG               (1 or 0) - If set to 1, engine will recompile scripts, if 0 - do nothing
    -c all                      clear all schema objects before run
    -c sp                       clear all stored procedures before run
    -c views                    clear all views before run
    -l locale                   locale to use e.g 'en'
    -p table_partition_number   Number of Columns at which to partition large Tables
    -u incremental_mode_switch  Configuration switch to turn on/off the incremental update feature

EOF
}

echo "ARG 1  : ${1:-}"
echo "ARG 2  : ${2:-}"
echo "ARG 3  : ${3:-}"
echo "ARG 4  : ${4:-}"
echo "ARG 5  : ${5:-}"
echo "ARG 6  : ${6:-}"
echo "ARG 7  : ${7:-}"
echo "ARG 8  : ${8:-}"
echo "ARG 9  : ${9:-}"
echo "ARG 10 : ${10:-}"
echo "ARG 11 : ${11:-}"
echo "ARG 12 : ${12:-}"
echo "ARG 13 : ${13:-}"
echo "ARG 14 : ${14:-}"
echo "ARG 15 : ${15:-}"
echo "ARG 16 : ${16:-}"

# Variable will contain the stored procedures for the Service layer Reports
# these are auto-generated by the engine from the reports.json file
create_report_procedure=""

# Variable will contain the MambaETL setup scripts
mamba_etl_starter_scripts=""

# Common function to read JSON configurations from config directory
# Parameters:
#   $1 - exclude_file: File to exclude (e.g., "reports.json")
# Returns:
#   JSON string with combined configurations
read_json_configurations() {
    local exclude_file="${1:-}"
    local json_contents="{\"flat_report_metadata\":["
    local first_file=true
    
    for filename in "${config_dir}"/*.json; do
        # Skip if file doesn't exist (no .json files)
        [[ ! -f "${filename}" ]] && continue
        
        # Skip excluded file
        if [[ -n "${exclude_file}" && "${filename}" = "${config_dir}/${exclude_file}" ]]; then
            continue
        fi
        
        # Add comma separator after first file
        if [[ "${first_file}" = false ]]; then
            json_contents="${json_contents},"
        fi
        
        json_contents="${json_contents}$(cat "${filename}")"
        first_file=false
    done
    
    json_contents="${json_contents}]}"
    
    # Validate JSON structure
    if ! echo "${json_contents}" | jq . > /dev/null 2>&1; then
        echo "Error: Invalid JSON structure in configuration files" >&2
        exit 1
    fi
    
    echo "${json_contents}"
}

# Common function to escape JSON for SQL
escape_json_for_sql() {
    local json="$1"
    # Escape single quotes for SQL safety
    echo "${json}" | sed "s/'/\\\\\\\\'\\\\\\\\'/g"
}

# Read in the Flat Table JSON configurations into the intermediary/consolidation table, mamba_flat_table_config
function read_config_metadata_into_mamba_flat_table_config() {
    # Read JSON configurations excluding reports.json
    local json_contents
    json_contents=$(read_json_configurations "reports.json")
    
    # Escape JSON for SQL
    local escaped_json
    escaped_json=$(escape_json_for_sql "${json_contents}")
    
    local sql_contents="
-- \$BEGIN

SET @report_data = '${escaped_json}';

CALL sp_mamba_flat_table_config_insert_helper_manual(@report_data); -- insert manually added config JSON data from config dir
CALL sp_mamba_flat_table_config_insert_helper_auto(); -- insert automatically generated config JSON data from db

-- \$END
"
    
    echo "${sql_contents}" > "../../database/${db_engine}/config/sp_mamba_flat_table_config_insert.sql"
}

# Read in the Flat Table JSON configurations into the intermediary/consolidation table (incremental table), mamba_flat_table_config_incremental
function read_config_metadata_into_mamba_flat_table_config_incremental() {
    # Read JSON configurations excluding reports.json
    local json_contents
    json_contents=$(read_json_configurations "reports.json")
    
    # Escape JSON for SQL
    local escaped_json
    escaped_json=$(escape_json_for_sql "${json_contents}")
    
    local sql_contents="
-- \$BEGIN

SET @report_data = '${escaped_json}';

CALL sp_mamba_flat_table_config_incremental_insert_helper_manual(@report_data); -- insert manually added config JSON data from config dir
CALL sp_mamba_flat_table_config_incremental_insert_helper_auto(); -- insert automatically generated config JSON data from db

-- \$END
"
    
    echo "${sql_contents}" > "../../database/${db_engine}/config/sp_mamba_flat_table_config_incremental_insert.sql"
}

# Read in the JSON configuration metadata from mamba_flat_table_config table into the mamba_concept_metadata table
function read_config_metadata_into_mamba_dim_concept_metadata() {

  SQL_CONTENTS="
-- \$BEGIN
"$'

SET @is_incremental = 0;
-- SET @report_data = fn_mamba_generate_json_from_mamba_flat_table_config(@is_incremental);
CALL sp_mamba_concept_metadata_insert_helper(@is_incremental, '\''mamba_concept_metadata'\'');

'"
-- \$END
"

  echo "$SQL_CONTENTS" > "../../database/${db_engine}/config/sp_mamba_concept_metadata_insert.sql" #TODO: improve!!
}

# Read in the JSON configuration metadata from mamba_flat_table_config table into the mamba_concept_metadata table (incrementally)
function read_config_metadata_into_mamba_dim_concept_metadata_incremental() {

  SQL_CONTENTS="
-- \$BEGIN
"$'

SET @is_incremental = 1;
-- SET @report_data = fn_mamba_generate_json_from_mamba_flat_table_config(@is_incremental);
CALL sp_mamba_concept_metadata_insert_helper(@is_incremental, '\''mamba_concept_metadata'\'');

'"
-- \$END
"

  echo "$SQL_CONTENTS" > "../../database/${db_engine}/config/sp_mamba_concept_metadata_incremental_insert.sql" #TODO: improve!!
}

# Read in the JSON configuration metadata for Table flattening
function read_config_metadata_for_incremental_comparison() {
    # Read JSON configurations excluding reports.json
    local json_contents
    json_contents=$(read_json_configurations "reports.json")
    
    # Count the number of JSON files excluding 'reports.json'
    local count
    count=$(find "${config_dir}" -type f -name '*.json' ! -name 'reports.json' | wc -l)
    
    # Escape JSON for SQL
    local escaped_json
    escaped_json=$(escape_json_for_sql "${json_contents}")
    
    local sql_contents="

  -- \$BEGIN

          SET @report_data = '${escaped_json}';
          SET @file_count = ${count};

          -- CALL sp_extract_configured_flat_table_file_into_dim_json_incremental(@report_data); -- insert manually added config JSON data from config dir
          -- CALL sp_mamba_dim_json_incremental_insert(); -- insert automatically generated config JSON data from db
          -- CALL sp_mamba_dim_json_incremental_update();

          -- SET @report_data = fn_mamba_generate_report_array_from_automated_json_incremental();
          CALL sp_mamba_extract_report_metadata(@report_data, 'mamba_concept_metadata');

  -- \$END
"
    
    echo "${sql_contents}" > "../../database/${db_engine}/config/sp_mamba_dim_concept_metadata_incremental_insert.sql" #TODO: improve!!
}

#Read in the locale setting
function read_locale_setting() {

  # Validate locale format (e.g., en, en_US, fr_FR)
  if [[ ! "$concepts_locale" =~ ^[a-z]{2}(_[A-Z]{2})?$ ]]; then
    echo "Error: Invalid locale format: $concepts_locale" >&2
    exit 1
  fi

  LOCALE_SP_SQL_CONTENTS="
-- \$BEGIN

  SET @concepts_locale = '${concepts_locale}';
  CALL sp_mamba_locale_insert_helper(@concepts_locale);

-- \$END
"

  echo "$LOCALE_SP_SQL_CONTENTS" > "../../database/${db_engine}/config/sp_mamba_dim_locale_insert.sql"
}

#Not using this function, Using a different approach - only left here for code reference purposes
function read_etl_user_settings() {

  USER_SETTINGS_SP_SQL_CONTENTS="

-- \$BEGIN
  "$'
  SET @concepts_locale = '%s';
  SET @table_partition = '%d';
  SET @incremental_switch = '%d';
  CALL sp_mamba_etl_user_settings_insert_helper(@concepts_locale, @table_partition, @incremental_switch);
  '"
-- \$END
"

  # Replace above placeholders in USER_SETTINGS_SP_SQL_CONTENTS with the actual values
  USER_SETTINGS_SP_SQL_CONTENTS=$(printf "$USER_SETTINGS_SP_SQL_CONTENTS" "'${concepts_locale}'" "${table_partition_number}" "${incremental_mode_switch}")

  echo "$USER_SETTINGS_SP_SQL_CONTENTS" > "../../database/${db_engine}/config/sp_mamba_etl_user_settings_insert.sql"
}

# Read the starter scripts for the MambaETL
function add_mamba_etl_starter_scripts() {


mamba_etl_starter_scripts+="

-- ---------------------------------------------------------------------------------------------
-- ----------------------------  Setup the MambaETL Scheduler  ---------------------------------
-- ---------------------------------------------------------------------------------------------


-- Enable the event etl_scheduler
SET GLOBAL event_scheduler = ON;

~-~-

-- Drop/Create the Event responsible for firing up the ETL process
DROP EVENT IF EXISTS _mamba_etl_scheduler_event;

~-~-

-- Drop/Create the Event responsible for maintaining event logs at a max. 20 elements
DROP EVENT IF EXISTS _mamba_etl_scheduler_trim_log_event;

~-~-

-- Setup ETL configurations
CALL sp_mamba_etl_setup(?, ?, ?, ?, ?, ?, ?);

-- pass them from the runtime properties file

~-~-

CREATE EVENT IF NOT EXISTS _mamba_etl_scheduler_event
    ON SCHEDULE EVERY ? SECOND
        STARTS CURRENT_TIMESTAMP
    DO CALL sp_mamba_etl_schedule();

~-~-

-- Setup a trigger that trims record off _mamba_etl_schedule to just leave 20 latest records.
-- to avoid the table growing too big

 CREATE EVENT IF NOT EXISTS _mamba_etl_scheduler_trim_log_event
    ON SCHEDULE EVERY 3 HOUR
        STARTS CURRENT_TIMESTAMP
    DO CALL sp_mamba_etl_schedule_trim_log_event();

 ~-~-
"
}

# Read in the JSON for Report Definition configuration metadata
function read_config_report_definition_metadata() {

    FILENAME="${config_dir}/reports.json";
    REPORT_DEFINITION_FILE="../../database/${db_engine}/config/sp_mamba_dim_report_definition_insert.sql"

    # Check if reports.json file exists
    if [ -s "$FILENAME" ] && [ -f "$FILENAME" ]; then
       json_string=$(cat "$FILENAME")

    else
      echo "reports.json file not found, is null or is not a regular file. Will not read report_definition."
      json_string='{"report_definitions": []}'

      echo "-- \$BEGIN" > "$REPORT_DEFINITION_FILE"
      echo "-- \$END" >> "$REPORT_DEFINITION_FILE"
      return
    fi

    # Get the total number of report_definitions
    total_reports=$(jq '.report_definitions | length' <<< "$json_string")

    # Clear the variable before the loop
    create_report_procedure=""

    # Iterate through each report_definition
    for ((i = 0; i < total_reports; i++)); do

        reportId=$(jq -r ".report_definitions[$i].report_id" <<< "$json_string")
        paginate_flag=$(jq ".report_definitions[$i].report_sql.paginate" <<< "$json_string") # Check if true

        report_procedure_name="sp_mamba_report_${reportId}_query"
        report_columns_procedure_name="sp_mamba_report_${reportId}_columns_query"
        report_size_procedure_name="sp_mamba_report_${reportId}_size_query" # Name for the count SP
        report_columns_table_name="mamba_report_$reportId"

        sql_query=$(jq -r ".report_definitions[$i].report_sql.sql_query" <<< "$json_string")
        # echo "SQL Query: $sql_query"

        # --- Generate IN parameters strings ---
        # 1. Parameters EXCLUDING pagination (for count query)
        in_query_parameters=""
        query_params_list=$(jq -c ".report_definitions[$i].report_sql.query_params[]? | select(length > 0) | {name, type}" <<< "$json_string") # Added ? for optional query_params
        while IFS= read -r entry; do
            queryName=$(jq -r '.name' <<< "$entry")
            queryType=$(jq -r '.type' <<< "$entry")
            if [[ -n "$queryName" && -n "$queryType" ]]; then
                in_query_parameters+="IN $queryName $queryType, "
            fi
        done <<< "$query_params_list"
        in_query_parameters="${in_query_parameters%, }" # Remove trailing comma

        # 2. Parameters INCLUDING pagination if needed (for main/columns query)
        in_parameters_with_pagination="$in_query_parameters"
        if [[ "$paginate_flag" == "true" ]]; then
            if [[ -n "$in_parameters_with_pagination" ]]; then
                 in_parameters_with_pagination+=", " # Add comma if other params exist
            fi
            # Add the standard pagination parameters
            in_parameters_with_pagination+="IN page_number INT, IN page_size INT"
        fi
        # --- End Parameter Generation ---

        # --- Generate Main Report SP Definition ---
        main_sp_body=""
        main_sp_params=""

        if [[ "$paginate_flag" == "true" ]]; then
            # For paginated reports, add offset calculation and LIMIT/OFFSET clause
            main_sp_params="$in_parameters_with_pagination"
            main_sp_body="
            DECLARE offset_val INT;
            SET offset_val = (page_number - 1) * page_size;
            -- Original query modified with LIMIT/OFFSET using calculated variable
            ${sql_query} LIMIT page_size OFFSET offset_val;"
        else
            # For non-paginated reports, use base query and non-pagination params
            main_sp_params="$in_query_parameters"
            main_sp_body="
            -- Original query (non-paginated)
            $sql_query;"
        fi

        create_report_procedure+="

-- ---------------------------------------------------------------------------------------------
-- ----------------------  $report_procedure_name  ----------------------------
-- ---------------------------------------------------------------------------------------------

DROP PROCEDURE IF EXISTS $report_procedure_name;

DELIMITER //

-- Parameters vary based on pagination flag
CREATE PROCEDURE $report_procedure_name($main_sp_params)
BEGIN

${main_sp_body}

END //

DELIMITER ;
"
        # --- End Main Report SP ---

        # --- Generate Columns Report SP Definition ---
        # Columns SP *always* uses LIMIT 0 internally, but accepts pagination params if needed for signature consistency
        create_report_procedure+="

-- ---------------------------------------------------------------------------------------------
-- ----------------------  $report_columns_procedure_name  ----------------------------
-- ---------------------------------------------------------------------------------------------

DROP PROCEDURE IF EXISTS $report_columns_procedure_name;

DELIMITER //

-- Accepts pagination params if main report is paginated (for signature consistency)
CREATE PROCEDURE $report_columns_procedure_name($in_parameters_with_pagination) -- Uses the full param list including pagination if applicable
BEGIN

-- Create Table to store report column names with no rows
DROP TABLE IF EXISTS $report_columns_table_name;

-- Use original query but *always* force LIMIT 0 to get structure without data
CREATE TABLE $report_columns_table_name AS
${sql_query} -- Base query from JSON
LIMIT 0;

-- Select report column names from the temporary table structure
-- Using information_schema might be slightly more robust if CREATE TABLE AS has issues
SELECT GROUP_CONCAT(COLUMN_NAME SEPARATOR ', ')
INTO @column_names
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE() -- Use current database
  AND TABLE_NAME = '$report_columns_table_name';

-- Update Table definition with report column names (optional, depends on your usage)
-- UPDATE mamba_dim_report_definition
-- SET result_column_names = @column_names
-- WHERE report_id='$reportId';

-- Return the column names as a result set
SELECT @column_names AS column_names;

-- Clean up the temporary table
DROP TABLE IF EXISTS $report_columns_table_name;

END //

DELIMITER ;

"
        # --- End Columns Report SP ---

        # --- Generate Count Query from Original SQL Query ---
        # Start with the original query
        count_query_temp="$sql_query"

        # Remove ORDER BY clause first (if it exists at the end, case-insensitive)
        count_query_temp=$(echo "$count_query_temp" | sed -E 's/ORDER BY +.*$//I')

        # Remove LIMIT ... OFFSET ... clause (if it exists at the end, case-insensitive)
        count_query_temp=$(echo "$count_query_temp" | sed -E 's/LIMIT +.* +OFFSET +.*$//I')

        # Remove LIMIT ... clause (if it exists at the end, case-insensitive)
        count_query_temp=$(echo "$count_query_temp" | sed -E 's/LIMIT +.*$//I')

        # Trim trailing whitespace that might be left after removals
        count_query_temp=$(echo "$count_query_temp" | sed -E 's/[[:space:]]*$//')

        # Replace the initial SELECT clause with SELECT COUNT(*) (case-insensitive, greedy)
        # This assumes the structure SELECT ... FROM ...
        count_query=$(echo "$count_query_temp" | sed -E 's/^SELECT.*FROM/SELECT COUNT(*) FROM/I')
        # --- End Count Query Generation ---

        # --- Generate Size/Count Report SP Definition ---
        # Only generate if paginate is true and the count query could be constructed
        if [[ -n "$count_query" && "$paginate_flag" == "true" ]]; then
            create_report_procedure+="
-- ---------------------------------------------------------------------------------------------
-- ----------------------  $report_size_procedure_name  ----------------------------
-- ---------------------------------------------------------------------------------------------

DROP PROCEDURE IF EXISTS $report_size_procedure_name;

DELIMITER //

-- Uses only non-pagination query parameters
CREATE PROCEDURE $report_size_procedure_name($in_query_parameters)
BEGIN

-- This query counts the total records based on the main query's criteria,
-- excluding pagination (LIMIT/OFFSET) and ordering (ORDER BY).
$count_query;

END //

DELIMITER ;

"
        fi
        # --- End Size/Count Report SP ---

    done # End of the loop iterating through report_definitions

    # Now Read in the contents for the Mysql Part - to insert into Tables
    if [ ! -z "$FILENAME" ] && [ -f "$FILENAME" ]; then

        # Validate JSON structure first
        if ! cat "$FILENAME" | jq . > /dev/null 2>&1; then
            echo "Error: Invalid JSON structure in reports.json file" >&2
            exit 1
        fi
        
        # Properly escape single quotes for SQL
        JSON_CONTENTS=$(cat "$FILENAME" | sed "s/'/\\\\'/g")

        REPORT_DEFINITION_CONTENT=$(cat <<EOF
-- \$BEGIN
SET @report_definition_json = '$JSON_CONTENTS';
CALL sp_mamba_extract_report_definition_metadata(@report_definition_json, 'mamba_dim_report_definition');
-- \$END
EOF
)
    fi

    echo "$REPORT_DEFINITION_CONTENT" > "$REPORT_DEFINITION_FILE" #TODO: improve!!
}

function make_buildfile_liquibase_compatible(){

  > "$cleaned_liquibase_file"

  end_pattern=r"^[[:space:]]*(end|END)[[:space:]]*[\r\n]*[/|//][[:space:]]*"
  delimiter_pattern=r"^[[:space:]]*(delimiter|DELIMITER)[[:space:]]*[\r\n]*[;|//][[:space:]]*"

  while IFS= read -r line; do

    if [[ "$line" =~ $end_pattern ]]; then
      echo "END~" >> "$cleaned_liquibase_file"
#      echo "~" >> "$cleaned_liquibase_file"
      continue
    fi

    if [[ "$line" =~ $delimiter_pattern ]]; then
      continue
    fi

    # Add the character '/' on a new line before the statement 'CREATE PROCEDURE...'
    if [[ $line == "CREATE PROCEDURE"* ]]; then
      echo "~" >> "$cleaned_liquibase_file"
    fi

     # Add the character '/' on a new line before the statement 'CREATE FUNCTION...'
    if [[ $line == "CREATE FUNCTION"* ]]; then
      echo "~" >> "$cleaned_liquibase_file"
    fi

    # Write the modified line to the output file
    echo "$line" >> "$cleaned_liquibase_file"

  done < "$file_to_clean"

  #after executing use analysis_db at strt of execution, we were getting a weir error in openmrs on unlocking liquibase changelock where it was looking for the Table inside analysis_db yet it is in the Openmrs transactional db
  #so let's manually change back to use the openmrs database at the end
  use_source_db="USE \`${source_database}\`;"
  echo "$use_source_db" >> "${cleaned_liquibase_file}"

}

function make_buildfile_jdbc_compatible(){

  > "$cleaned_jdbc_file"

  end_pattern="^[[:space:]]*(end|END)[[:space:]]*[/|//][[:space:]]*"
  delimiter_pattern="^[[:space:]]*(delimiter|DELIMITER)[[:space:]]*[;|//][[:space:]]*"

  while IFS= read -r line; do

    if [[ "$line" =~ $end_pattern ]]; then
      echo "END;" >> "$cleaned_jdbc_file"
      echo "~-~-" >> "$cleaned_jdbc_file"
      continue
    fi

    if [[ "$line" =~ $delimiter_pattern ]]; then
      continue
    fi

    # Add the character '/' on a new line before the statement 'CREATE PROCEDURE...'
    if [[ $line == "CREATE PROCEDURE"* ]]; then
      echo "~-~-" >> "$cleaned_jdbc_file"
    fi

     # Add the character '/' on a new line before the statement 'CREATE FUNCTION...'
    if [[ $line == "CREATE FUNCTION"* ]]; then
       echo "~-~-" >> "$cleaned_jdbc_file"

    fi

    # Write the modified line to the output file
    echo "$line" >> "$cleaned_jdbc_file"

  done < "$file_to_clean"
}

function consolidateSPsCallerFile() {

  # Save the current directory
  local currentDir=$(pwd)

  # Get the base dir for the db engine we are working with
  local dbEngineBaseDir=$(readlink -f "../../database/${db_engine}")

  # Search for core's p_data_processing.sql file in all subdirectories in the path: ${project.build.directory}/mamba-etl/_core/database/$db_engine
  #  local consolidatedFile=$(find "../../database/$db_engine" -name sp_mamba_data_processing_drop_and_flatten.sql -type f -print -quit)
  local consolidatedFile=$(find "$dbEngineBaseDir" -name sp_makefile -type f -print -quit)

  # Search for all files with the specified filename in the path: ${project.build.directory}/mamba-etl/_etl
  # Then get its directory name/path, so we can find a file named sp_mamba_data_processing_drop_and_flatten.sql which is in the same dir
  local sp_make_folders=$(find "../../../_etl" -name sp_makefile -type f -exec dirname {} \; | sort -u)

  local newLine="\n"
  local formatHash="#############################################################################"

  printf "\n" >> "$consolidatedFile"
  printf "\n" >> "$consolidatedFile"
  echo $formatHash >> "$consolidatedFile"
  printf "############################### ETL Scripts #################################" >> "$consolidatedFile"
  printf "\n" >> "$consolidatedFile"
  echo $formatHash >> "$consolidatedFile"

  # Loop through each folder, cd to that folder
  local temp_folder_number=1
  for folder in $sp_make_folders; do

    cd "$folder"

    printf "\n" >> "$consolidatedFile"

    # Read the sp_makefile line by line skipping comments (#) and write the file and its dir structure to a new loc.
    cat sp_makefile | grep -v "^#" | grep -v "^$" | while read -r line; do

      # echo "copying file: $line"
      # echo "to temp location: $dbEngineBaseDir"/etl/$temp_folder_number

      # Extract the file name and folder name from the line
      # filename=$(basename "$line")
      # foldername=$(dirname "$line")

      # Output the file name and folder name to the console
      #echo "File name: $filename"
      #echo "Folder name: $foldername"

      #Copy the file with its full path and folder structure to the temp folder
      rsync --relative "$line" "$dbEngineBaseDir"/etl/$temp_folder_number/

      # copy the new file path to the consolidated file
      echo "etl/$temp_folder_number/$line" >>"$consolidatedFile"

    done

    temp_folder_number=$((temp_folder_number + 1))
    cd "$currentDir"
  done

}

function create_directory_if_absent(){
    local DIR="$1"

    if [ ! -d "${DIR}" ]; then
        mkdir -p "${DIR}"
    fi
}

function exit_if_file_absent(){
    local FILE="$1"
    if [ ! -f "${FILE}" ]; then
        echo "We couldn't find this file. Please correct and try again" >&2
        echo "${FILE}" >&2
        exit 1
    fi
}

# Remove the first 2 occurences of the tilde (~) from a file passed as an argument
function remove_tildes_in_sql_build_file () {

    # Get the file path from the first argument
    local build_file="$1"

    # Create a temporary file to write contents without the first two tildes
    local temp_file_no_tildes=$(mktemp)

    # Use sed to remove only the first two occurrences of the tilde character
    sed 's/~//' "$build_file" | sed 's/~//' > "$temp_file_no_tildes"

    # Overwrite the original file with the content of the temporary file
    mv "$temp_file_no_tildes" "$build_file"

    # Remove the temporary file
    rm "$temp_file_no_tildes"
}

# copy mamba_main.sql to the build directory
function copy_mamba_main_sql_to_build_dir() {

    SOURCE_FILE="../../database/${db_engine}/mamba_main.sql"

    # Extract the file name from the source path
    FILE_NAME=$(basename "$SOURCE_FILE")

    DESTINATION_FILE="$BUILD_DIR/$FILE_NAME"

    if cp "$SOURCE_FILE" "$DESTINATION_FILE"; then
        echo "mamba main sql file copied successfully to $DESTINATION_FILE."
    else
        echo "BUILD_DIR: $BUILD_DIR"
        echo "Failed to copy $SOURCE_FILE to $DESTINATION_FILE" >&2
        return 1
    fi
}


BUILD_DIR=""
sp_out_file="create_stored_procedures.sql"
vw_out_file="create_views.sql"
makefile=""
source_database=""
analysis_database=""
concepts_locale=""
table_partition_number=""
incremental_mode_switch=""
config_dir=""
cleaned_liquibase_file=""
cleaned_jdbc_file=""
file_to_clean=""
db_engine=""
views=""
stored_procedures=""
schema=""
objects=""
OPTIND=1
IFS='
'

while getopts ":h:t:n:d:a:v:s:k:o:c:l:p:u:" opt; do
    case "${opt}" in
        h)
            show_help
            exit 0
            ;;
        t)  
            config_dir="$OPTARG"
            # Validate config directory exists and is readable
            if [[ ! -d "${config_dir}" ]]; then
                echo "Error: Config directory does not exist: ${config_dir}" >&2
                exit 1
            fi
            if [[ ! -r "${config_dir}" ]]; then
                echo "Error: Config directory is not readable: ${config_dir}" >&2
                exit 1
            fi
            ;;
        n)  
            db_engine="$OPTARG"
            # Validate db_engine
            if [[ "${db_engine}" != "mysql" ]]; then
                echo "Error: Only mysql is currently supported, got: ${db_engine}" >&2
                exit 1
            fi
            ;;
        d)  
            source_database="$OPTARG"
            validate_database_name "${source_database}"
            ;;
        a)  
            analysis_database="$OPTARG"
            validate_database_name "${analysis_database}"
            ;;
        v)  
            views="$OPTARG"
            ;;
        s)  
            stored_procedures="$OPTARG"
            ;;
        k)  
            schema="$OPTARG"
            validate_schema_name "${schema}"
            ;;
        o)  
            out_file="$OPTARG"
            # Validate output file path
            if [[ "${out_file}" =~ \.\./ ]] || [[ "${out_file}" =~ ^/ ]]; then
                echo "Error: Output file must be relative to current directory: ${out_file}" >&2
                exit 1
            fi
            ;;
        c)  
            objects="$OPTARG"
            # Validate objects to clear
            if [[ "${objects}" != "all" && "${objects}" != "sp" && "${objects}" != "views" && "${objects}" != "view" && "${objects}" != "v" ]]; then
                echo "Error: Invalid objects value: ${objects}. Must be one of: all, sp, views, view, v" >&2
                exit 1
            fi
            ;;
        l)  
            concepts_locale="$OPTARG"
            # Validate locale format (e.g., en, en_US, fr_FR)
            if [[ ! "${concepts_locale}" =~ ^[a-z]{2}(_[A-Z]{2})?$ ]]; then
                echo "Error: Invalid locale format: ${concepts_locale}" >&2
                exit 1
            fi
            ;;
        p)  
            table_partition_number="$OPTARG"
            validate_integer "${table_partition_number}" "table_partition_number" 1 1000
            ;;
        u)  
            incremental_mode_switch="$OPTARG"
            validate_integer "${incremental_mode_switch}" "incremental_mode_switch" 0 1
            ;;
        *)
            echo "Error: Invalid option: -${OPTARG}" >&2
            show_help >&2
            exit 1
            ;;
    esac
done
shift "$((OPTIND-1))"

if [ ! -n "$stored_procedures" ] && [ ! -n "$views" ]
then
    show_help >&2
    exit 1
fi

if [ -n "$views" ] && [ -n "$stored_procedures" ] && [ -n "$out_file" ]
then
    echo "Warning: You can not compile both views and stored procedures if you provide an output file."
    exit 1
fi

if [ -n "$out_file" ]
then
    sp_out_file=$out_file
    vw_out_file=$out_file
fi

schema_name="$schema"
if [ ! -n "$schema" ]
then
    schema_name="dbo"
else
    schema_name="$schema"
fi

objects_to_clear="$objects"
if [ ! -n "$objects" ]
then
    objects_to_clear=""
else
    objects_to_clear="$objects"
fi

clear_message="No objects to clean out."
clear_objects_sql=""
if [ "$objects_to_clear" == "all" ]; then
    clear_message="clearing all objects in $schema_name"
    clear_objects_sql="CALL dbo.sp_xf_system_drop_all_objects_in_schema '$schema_name' "
elif [ "$objects_to_clear" == "sp" ]; then
    clear_message="clearing all stored procedures in $schema_name"
    clear_objects_sql="CALL dbo.sp_xf_system_drop_all_stored_procedures_in_schema '$schema_name' "
elif [ "$objects_to_clear" == "views" ] || [ "$objects_to_clear" == "view" ] || [ "$objects_to_clear" == "v" ]; then
    clear_message="clearing all views in $schema_name"
    clear_objects_sql="CALL dbo.sp_xf_system_drop_all_views_in_schema '$schema_name' "
fi

# Read in the concepts locale setting
# Got a better implementation so commenting this code out
# read_locale_setting

# Read in the JSON for Report Definition configuration metadata
read_config_report_definition_metadata

# Add the startup scripts for the ETL
add_mamba_etl_starter_scripts

# Read in the Flat Table JSON configurations into the intermediary/consolidation table, mamba_flat_table_config
read_config_metadata_into_mamba_flat_table_config

# Read in the Flat Table JSON configurations into the intermediary/consolidation table (incremental table), mamba_flat_table_config_incremental
read_config_metadata_into_mamba_flat_table_config_incremental

# Read in the JSON configuration metadata from mamba_flat_table_config table into the mamba_concept_metadata table
read_config_metadata_into_mamba_dim_concept_metadata

# Read in the JSON configuration metadata from mamba_flat_table_config table into the mamba_concept_metadata table (incrementally)
read_config_metadata_into_mamba_dim_concept_metadata_incremental

# TODO: Delete after Read in the JSON configuration metadata for incremental comparison
read_config_metadata_for_incremental_comparison

# Consolidate all the make files into one file
consolidateSPsCallerFile


if [ -n "$stored_procedures" ]
then

    makefile=$stored_procedures
    exit_if_file_absent "$makefile"

    WORKING_DIR=$(dirname "$makefile")
    BUILD_DIR="$WORKING_DIR/build"
    create_directory_if_absent "$BUILD_DIR"

    # all_stored_procedures="USE $analysis_database;
    all_stored_procedures="
        $clear_objects_sql
    "

    if [ ! -n "$source_database" ]
    then
        all_stored_procedures=""
    fi

    if [ ! -n "$analysis_database" ]
    then
        all_stored_procedures=""
    fi

    # if any of the files doesn't exist, do not process
    while IFS= read -r file_path; do
        # Skip empty lines and comments
        [[ -z "$file_path" || "$file_path" =~ ^# ]] && continue
        
        # Validate path to prevent traversal
        validated_path=$(validate_path "${WORKING_DIR}/${file_path}" "${WORKING_DIR}")
        
        if [ ! -f "${validated_path}" ]; then
            echo "Warning: Could not process stored procedures. File '${file_path}' does not exist." >&2
            exit 1
        fi
    done < <(sed -E '/^[[:blank:]]*(#|$)/d; s/#.*//' "${makefile}")

    sp_name=""

    while IFS= read -r file_path; do
        # Skip empty lines and comments
        [[ -z "$file_path" || "$file_path" =~ ^# ]] && continue
        
        # Validate path to prevent traversal
        validated_path=$(validate_path "${WORKING_DIR}/${file_path}" "${WORKING_DIR}")
        
        # create a stored procedure
        file_name=$(basename "${file_path}" ".sql")
        sp_name="${file_name}"
        sp_body=$(awk '/-- \$BEGIN/,/-- \$END/' "${validated_path}")

        prefix='-- $BEGIN'
        suffix='-- $END'

        #sp_body=${sp_body#"$prefix"}
        #sp_body=${sp_body%"$suffix"}

        if [ -z "$sp_body" ]
        then
              sp_body=`cat $WORKING_DIR/$file_path`
              sp_create_statement="
-- ---------------------------------------------------------------------------------------------
-- $sp_name
--

$sp_body

"
        else
            sp_create_statement="
-- ---------------------------------------------------------------------------------------------
-- $sp_name
--

DROP PROCEDURE IF EXISTS $sp_name;

DELIMITER //

CREATE PROCEDURE $sp_name()
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
    GET DIAGNOSTICS CONDITION 1

    @message_text = MESSAGE_TEXT,
    @mysql_errno = MYSQL_ERRNO,
    @returned_sqlstate = RETURNED_SQLSTATE;

    CALL sp_mamba_etl_error_log_insert('$sp_name', @message_text, @mysql_errno, @returned_sqlstate);

    UPDATE _mamba_etl_schedule
    SET end_time                   = NOW(),
        completion_status          = 'ERROR',
        transaction_status         = 'COMPLETED',
        success_or_error_message   = CONCAT('$sp_name', ', ', @mysql_errno, ', ', @message_text)
        WHERE id = (SELECT last_etl_schedule_insert_id FROM _mamba_etl_user_settings ORDER BY id DESC LIMIT 1);

    RESIGNAL;
END;

$sp_body
END //

DELIMITER ;
"
        fi

        all_stored_procedures="$all_stored_procedures
        $sp_create_statement"
    done < <(sed -E '/^[[:blank:]]*(#|$)/d; s/#.*//' "${makefile}")

    ### SG - replace any place holders in the script e.g.$target_database
    ### all_stored_procedures="${all_stored_procedures//'$target_database'/'$analysis_database'}" commented out since we are not using it now
    ### all_stored_procedures="${all_stored_procedures//\$target_database/'$analysis_database'}" even this works!!

    ### Add the reporting SPs created above if any
    all_stored_procedures+="$create_report_procedure"

    ### Add the MambaETL starter scripts that schedule the ETL
    all_stored_procedures+="$mamba_etl_starter_scripts"

    ### write built contents (final SQL file contents) to the build output file
    echo "$all_stored_procedures" > "$BUILD_DIR/$sp_out_file"

    ### SG - Clean up build file to make it Liquibase compatible ###
    file_to_clean="$BUILD_DIR/$sp_out_file"

    ## Automate the Create Analysis Database command at the beginning of the script
    ## Dynamically get charset and collation from source database to ensure compatibility
    create_target_db="-- Get source database charset and collation, then create ETL database with same settings
SET @source_charset = (SELECT DEFAULT_CHARACTER_SET_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'mamba_source_db');
SET @source_collation = (SELECT DEFAULT_COLLATION_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'mamba_source_db');

-- Use default charset/collation if source database is not found
SET @source_charset = IFNULL(@source_charset, 'utf8mb4');
SET @source_collation = IFNULL(@source_collation, 'utf8mb4_unicode_ci');

-- Set session charset/collation to match source database (prevents collation mismatches with variables)
SET @set_names_sql = CONCAT('SET NAMES ', @source_charset, ' COLLATE ', @source_collation);
PREPARE stmt FROM @set_names_sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Create the ETL database with the same charset and collation as the source
SET @create_db_sql = CONCAT('CREATE DATABASE IF NOT EXISTS mamba_etl_db CHARACTER SET ', @source_charset, ' COLLATE ', @source_collation);
PREPARE stmt FROM @create_db_sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;"$'\n~-~-\n'

    ## Add the target database to use at the beginning of the script
    use_target_db="USE mamba_etl_db;"$'\n~-~-\n'

    # Create a temporary file with the text to prepend
    temp_file=$(mktemp)

    # Add 'create database' command text to the temporary file
    echo "$create_target_db" > "$temp_file"

    # Append 'use database' command text to the temporary file
    echo "$use_target_db" >> "$temp_file"

    # Append the original file's content to the temporary file
    cat "$file_to_clean" >> "$temp_file"

    # Overwrite the original file with the contents of the temporary file
    mv "$temp_file" "$file_to_clean"

    # Create OpenMRS deployable build file before replacing mamba_source_db placeholder cuz this is replaced in Java
    # for the create_stored_procedures build file, that one can contain whatever has been passed via pom.xml for test purposes
    cleaned_jdbc_file="$BUILD_DIR/jdbc_$sp_out_file"
    make_buildfile_jdbc_compatible

    # Remove the temporary file
    rm "$temp_file"

     ## Replace source database placeholder name
     temp_file=$(mktemp)

    # Validate database names before using them
    validate_database_name "${analysis_database}"
    validate_database_name "${source_database}"
    
    # Search for any occurrences of 'mamba_etl_db' and 'mamba_source_db' and  awk to perform the replacement
    awk -v analysis_db="${analysis_database}" -v source_db="${source_database}" \
        '{ gsub("mamba_etl_db", analysis_db); gsub("mamba_source_db", source_db); print }' \
        "${file_to_clean}" > "${temp_file}"

    # Overwrite the original file with the contents of the temporary file
    mv "$temp_file" "$file_to_clean"

    # Remove the temporary file
    rm "$temp_file"

    cleaned_liquibase_file="$BUILD_DIR/liquibase_$sp_out_file"
    make_buildfile_liquibase_compatible

    #remove tilde characters from the build files
    remove_tildes_in_sql_build_file "$BUILD_DIR/$sp_out_file"
    #remove_tildes_in_sql_build_file "$cleaned_jdbc_file"
fi

if [ -n "$views" ]
then

    makefile=$views
    exit_if_file_absent "$makefile"

    WORKING_DIR=$(dirname "$makefile")
    BUILD_DIR="$WORKING_DIR/build"
    create_directory_if_absent "$BUILD_DIR"

    # views_body="USE $analysis_database;
    views_body="

$clear_objects_sql

"
    if [ ! -n "$source_database" ]
    then
        views_body=""
    fi

    if [ ! -n "$analysis_database" ]
    then
        views_body=""
    fi

    # if any of the files doesnt exist, do not process
    while IFS= read -r file_path; do
        # Skip empty lines and comments
        [[ -z "$file_path" || "$file_path" =~ ^# ]] && continue
        
        # Validate path to prevent traversal
        validated_path=$(validate_path "${WORKING_DIR}/${file_path}" "${WORKING_DIR}")
        
        if [ ! -f "${validated_path}" ]; then
            echo "Warning: Could not process. File '${file_path}' does not exist." >&2
            exit 1
        fi
    done < <(sed -E '/^[[:blank:]]*(#|$)/d; s/#.*//' "${makefile}")

    while IFS= read -r file_path; do
        # Skip empty lines and comments
        [[ -z "$file_path" || "$file_path" =~ ^# ]] && continue
        
        # Validate path to prevent traversal
        validated_path=$(validate_path "${WORKING_DIR}/${file_path}" "${WORKING_DIR}")
        
        # create view
        file_name=$(basename "${file_path}" ".sql")
        vw_name="${file_name}"
        vw_body=$(awk '/-- \$BEGIN/,/-- \$END/' "${validated_path}")

        vw_header="

-- ---------------------------------------------------------------------------------------------
-- $vw_name
--

CREATE OR ALTER VIEW $vw_name AS
"

views_body="$views_body
$vw_header
$vw_body

"
    done < <(sed -E '/^[[:blank:]]*(#|$)/d; s/#.*//' "${makefile}")

    echo "$views_body" > "$BUILD_DIR/$vw_out_file"

fi

# function to copy mamba_main.sql to the build directory
copy_mamba_main_sql_to_build_dir
